# Generated by Django 5.2.7 on 2025-10-10 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalaxyInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.URLField()),
                ('api_key', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('timeout', models.PositiveIntegerField(default=30)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GalaxyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galaxy_history_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('ok', 'Completed'), ('error', 'Error'), ('deleted', 'Deleted')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('galaxy_created_at', models.DateTimeField(blank=True, null=True)),
                ('galaxy_data', models.JSONField(blank=True, default=dict)),
                ('galaxy_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='galaxy_integration.galaxyinstance')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('galaxy_instance', 'galaxy_history_id')},
            },
        ),
        migrations.CreateModel(
            name='GalaxyDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galaxy_dataset_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('ok', 'Completed'), ('error', 'Error'), ('deleted', 'Deleted')], default='new', max_length=20)),
                ('is_vcf', models.BooleanField(default=False)),
                ('vcf_sample_count', models.PositiveIntegerField(blank=True, null=True)),
                ('vcf_variant_count', models.PositiveIntegerField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('local_file_path', models.CharField(blank=True, max_length=500)),
                ('download_url', models.URLField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('galaxy_created_at', models.DateTimeField(blank=True, null=True)),
                ('galaxy_data', models.JSONField(blank=True, default=dict)),
                ('galaxy_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='galaxy_integration.galaxyhistory')),
                ('galaxy_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='galaxy_integration.galaxyinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalaxyAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(max_length=100)),
                ('api_key', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('galaxy_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='galaxy_integration.galaxyinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalaxySyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('items_processed', models.PositiveIntegerField(default=0)),
                ('items_total', models.PositiveIntegerField(default=0)),
                ('items_failed', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('job_config', models.JSONField(blank=True, default=dict)),
                ('galaxy_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='galaxy_integration.galaxyinstance')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalaxyWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galaxy_workflow_id', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('galaxy_data', models.JSONField(blank=True, default=dict)),
                ('galaxy_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='galaxy_integration.galaxyinstance')),
                ('input_datasets', models.ManyToManyField(blank=True, related_name='input_workflows', to='galaxy_integration.galaxydataset')),
                ('output_datasets', models.ManyToManyField(blank=True, related_name='output_workflows', to='galaxy_integration.galaxydataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='galaxydataset',
            index=models.Index(fields=['is_vcf', 'is_processed'], name='galaxy_inte_is_vcf_e3fde2_idx'),
        ),
        migrations.AddIndex(
            model_name='galaxydataset',
            index=models.Index(fields=['status'], name='galaxy_inte_status_8e8e5e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='galaxydataset',
            unique_together={('galaxy_instance', 'galaxy_dataset_id')},
        ),
        migrations.AlterUniqueTogether(
            name='galaxyapikey',
            unique_together={('galaxy_instance', 'key_name')},
        ),
        migrations.AlterUniqueTogether(
            name='galaxyworkflow',
            unique_together={('galaxy_instance', 'galaxy_workflow_id')},
        ),
    ]
