# Generated by Django 4.2.7 on 2025-11-12 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerTrendPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('prediction_horizon_days', models.PositiveIntegerField(default=30)),
                ('trend_direction', models.CharField(choices=[('increasing', 'Increasing'), ('decreasing', 'Decreasing'), ('stable', 'Stable'), ('volatile', 'Volatile')], max_length=20)),
                ('confidence_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('predicted_variant_counts', models.JSONField(blank=True, default=list)),
                ('prediction_dates', models.JSONField(blank=True, default=list)),
                ('confidence_intervals', models.JSONField(blank=True, default=list)),
                ('key_trends', models.JSONField(blank=True, default=list)),
                ('significant_genes', models.JSONField(blank=True, default=list)),
                ('clinical_patterns', models.JSONField(blank=True, default=list)),
                ('drug_implications', models.JSONField(blank=True, default=list)),
                ('risk_assessment', models.TextField(blank=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('trend_chart_data', models.JSONField(blank=True, default=dict)),
                ('gene_chart_data', models.JSONField(blank=True, default=dict)),
                ('data_source_period_days', models.PositiveIntegerField(default=180)),
                ('total_variants_analyzed', models.PositiveIntegerField(default=0)),
                ('model_version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cancer Trend Prediction',
                'verbose_name_plural': 'Cancer Trend Predictions',
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['prediction_date'], name='variants_ca_predict_156ca2_idx'), models.Index(fields=['trend_direction'], name='variants_ca_trend_d_2c3f81_idx'), models.Index(fields=['confidence_score'], name='variants_ca_confide_9b0b5b_idx')],
            },
        ),
    ]
